# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frekuensi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import nltk
import sys
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from nltk import tokenize

data_cleanpositif = pd.read_csv(
    'C:\data_cleanpositif.csv', encoding='latin1')
token_space = tokenize.WhitespaceTokenizer()
all_words = ' '.join(
    [tweet for tweet in data_cleanpositif['Content'].astype('str')])
token_phrase = token_space.tokenize(all_words)
frequency = nltk.FreqDist(token_phrase)
df_frequency = pd.DataFrame(
    {"Word": list(frequency.keys()), "Frequency": list(frequency.values())})
df_frequency = df_frequency.nlargest(columns="Frequency", n=5)
plt.figure(figsize=(6, 4))
ax = sns.barplot(data=df_frequency, x="Word",
                 y="Frequency", palette='deep')
ax.set(ylabel="Count")
plt.xticks(rotation='vertical')
plt.tight_layout()
plt.show()
