# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KlasifikasiMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import nltk
import string
import re
import pandas as pd
import numpy as np
from PyQt5 import QtCore, QtGui, QtWidgets
import subprocess
from pathlib import Path


class Ui_Form(object):

    def frekuensikata(self):
        cmd = 'frekuensitest.py'
        p = subprocess.Popen(cmd, shell=True)
        out, err = p.communicate()
        print(err)
        print(out)

    def tabelmenu(self):
        cmd = 'MenuTable.py'
        p = subprocess.Popen(cmd, shell=True)
        out, err = p.communicate()
        print(err)
        print(out)

    def updatelabel(self, persen):
        global splitpersen
        self.label_14.setText(str(persen)+'%')
        ntest = persen-100
        ntest1 = abs(ntest)
        splitpersen = ntest1/100
        print(splitpersen)
        self.label_15.setText(str(ntest1)+'%')

    def browser(self):
        global filename
        qfd = QtWidgets.QFileDialog()
        path = "C:"
        filter = "csv(*.csv)"
        fname = QtWidgets.QFileDialog.getOpenFileName(
            qfd, 'Open File', path, filter)
        filename = fname[0]
        print(filename)
        file_path = filename
        file_name = Path(file_path).stem
        print(file_name)
        self.label_19.setText(file_name+'.csv')
        return fname

    def klasifikasi(self):
        filecsv = filename
        data = pd.read_csv(filecsv, header=0, usecols=[
            'Content', 'senti'], delimiter=',', encoding='utf-8')
        data_clean = pd.DataFrame(data)
        print(data_clean)
        data_clean = data_clean.astype({'senti': 'category'})
        data_clean = data_clean.astype({'Content': 'string'})
        data_clean.dtypes

        # Tfidf
        from sklearn.feature_extraction.text import CountVectorizer
        from sklearn.feature_extraction.text import TfidfVectorizer
        tf = TfidfVectorizer()
        text_tf = tf.fit_transform(data_clean['Content'].astype('U'))
        text_tf

        # splitting data
        from sklearn.model_selection import train_test_split
        X_train, X_text, y_train, y_text = train_test_split(
            text_tf, data_clean['senti'], test_size=splitpersen, random_state=42)
        self.nacu_2.setText(str(y_train.count()))
        self.nacu_3.setText(str(y_text.count()))

        # Klasifikasi akurasi
        from sklearn.naive_bayes import MultinomialNB
        from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
        from sklearn.metrics import classification_report
        from sklearn.metrics import confusion_matrix

        clf = MultinomialNB().fit(X_train, y_train)
        predicted = clf.predict(X_text)

        print("NB Accuaracy : ", accuracy_score(y_text, predicted))
        print("NB Precision : ", precision_score(
            y_text, predicted, average="binary", pos_label="negatif"))
        print("NB Recall : ", recall_score(
            y_text, predicted, average="binary", pos_label="negatif"))
        print("NB f1 : ", f1_score(y_text, predicted,
                                   average="binary", pos_label="negatif"))
        print(
            f'confusion matrix:\n {confusion_matrix(y_text,predicted)}')
        print('======================================================\n')
        print(classification_report(y_text, predicted, zero_division=0))
        accu = accuracy_score(y_text, predicted)
        self.nacu.setText(str(accuracy_score(y_text, predicted)))
        self.npre.setText(str(precision_score(
            y_text, predicted, average="binary", pos_label="negatif")))
        self.nrec.setText(str(recall_score(
            y_text, predicted, average="binary", pos_label="negatif")))
        self.nf1.setText(str(f1_score(y_text, predicted,
                                      average="binary", pos_label="negatif")))
        self.conmat.setText(str(confusion_matrix(y_text, predicted)))
        self.clasifireport.setText(
            str(classification_report(y_text, predicted, zero_division=0)))

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(612, 360)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 51, 16))
        self.label_2.setObjectName("label_2")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(0, 30, 311, 41))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(110, 50, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.toolButton = QtWidgets.QToolButton(Form)
        self.toolButton.setGeometry(QtCore.QRect(214, 100, 61, 20))
        self.toolButton.setObjectName("toolButton")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(80, 200, 151, 31))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(400, 50, 111, 21))
        self.label_3.setObjectName("label_3")
        self.line_5 = QtWidgets.QFrame(Form)
        self.line_5.setGeometry(QtCore.QRect(0, 230, 311, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 310, 131, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(50, 80, 231, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(330, 80, 121, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(330, 100, 101, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(330, 120, 91, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(330, 140, 91, 16))
        self.label_8.setObjectName("label_8")
        self.clasifireport = QtWidgets.QLabel(Form)
        self.clasifireport.setGeometry(QtCore.QRect(330, 230, 251, 121))
        self.clasifireport.setText("")
        self.clasifireport.setObjectName("clasifireport")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(330, 160, 101, 20))
        self.label_11.setObjectName("label_11")
        self.nacu = QtWidgets.QLabel(Form)
        self.nacu.setGeometry(QtCore.QRect(440, 80, 51, 16))
        self.nacu.setText("")
        self.nacu.setObjectName("nacu")
        self.npre = QtWidgets.QLabel(Form)
        self.npre.setGeometry(QtCore.QRect(440, 100, 51, 16))
        self.npre.setText("")
        self.npre.setObjectName("npre")
        self.nrec = QtWidgets.QLabel(Form)
        self.nrec.setGeometry(QtCore.QRect(440, 120, 51, 16))
        self.nrec.setText("")
        self.nrec.setObjectName("nrec")
        self.nf1 = QtWidgets.QLabel(Form)
        self.nf1.setGeometry(QtCore.QRect(440, 140, 51, 16))
        self.nf1.setText("")
        self.nf1.setObjectName("nf1")
        self.conmat = QtWidgets.QLabel(Form)
        self.conmat.setGeometry(QtCore.QRect(440, 160, 81, 41))
        self.conmat.setText("")
        self.conmat.setObjectName("conmat")
        self.line_6 = QtWidgets.QFrame(Form)
        self.line_6.setGeometry(QtCore.QRect(310, 210, 301, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(410, 200, 101, 20))
        self.label_17.setObjectName("label_17")
        self.line_7 = QtWidgets.QFrame(Form)
        self.line_7.setGeometry(QtCore.QRect(310, 60, 301, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalSlider = QtWidgets.QSlider(Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(100, 160, 111, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(120, 130, 71, 16))
        self.label_9.setObjectName("label_9")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(40, 140, 51, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(220, 140, 47, 16))
        self.label_13.setObjectName("label_13")
        self.line_8 = QtWidgets.QFrame(Form)
        self.line_8.setGeometry(QtCore.QRect(0, 120, 311, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_11 = QtWidgets.QFrame(Form)
        self.line_11.setGeometry(QtCore.QRect(-10, 180, 321, 20))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(Form)
        self.line_12.setGeometry(QtCore.QRect(0, 100, 311, 41))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(50, 160, 31, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(230, 160, 31, 16))
        self.label_15.setObjectName("label_15")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(500, 80, 61, 16))
        self.label_10.setObjectName("label_10")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(500, 100, 61, 16))
        self.label_16.setObjectName("label_16")
        self.nacu_2 = QtWidgets.QLabel(Form)
        self.nacu_2.setGeometry(QtCore.QRect(560, 80, 51, 16))
        self.nacu_2.setText("")
        self.nacu_2.setObjectName("nacu_2")
        self.nacu_3 = QtWidgets.QLabel(Form)
        self.nacu_3.setGeometry(QtCore.QRect(560, 100, 51, 16))
        self.nacu_3.setText("")
        self.nacu_3.setObjectName("nacu_3")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(310, 40, 301, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(60, 250, 191, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(60, 280, 191, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.line_13 = QtWidgets.QFrame(Form)
        self.line_13.setGeometry(QtCore.QRect(0, -10, 651, 41))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(210, 10, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.line_14 = QtWidgets.QFrame(Form)
        self.line_14.setGeometry(QtCore.QRect(0, 20, 651, 41))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(Form)
        self.line_15.setGeometry(QtCore.QRect(300, 40, 20, 321))
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(Form)
        self.line_16.setGeometry(QtCore.QRect(0, 60, 311, 20))
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.line_17 = QtWidgets.QFrame(Form)
        self.line_17.setGeometry(QtCore.QRect(310, 190, 301, 20))
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(100, 100, 111, 16))
        self.label_19.setObjectName("label_19")
        self.label_4.raise_()
        self.line_5.raise_()
        self.line_12.raise_()
        self.line_8.raise_()
        self.line_11.raise_()
        self.label_2.raise_()
        self.line.raise_()
        self.line_14.raise_()
        self.line_2.raise_()
        self.label.raise_()
        self.toolButton.raise_()
        self.pushButton.raise_()
        self.label_3.raise_()
        self.pushButton_2.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.clasifireport.raise_()
        self.label_11.raise_()
        self.nacu.raise_()
        self.npre.raise_()
        self.nrec.raise_()
        self.nf1.raise_()
        self.conmat.raise_()
        self.line_6.raise_()
        self.label_17.raise_()
        self.line_7.raise_()
        self.horizontalSlider.raise_()
        self.label_9.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_10.raise_()
        self.label_16.raise_()
        self.nacu_2.raise_()
        self.nacu_3.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.line_13.raise_()
        self.label_18.raise_()
        self.line_15.raise_()
        self.line_16.raise_()
        self.line_17.raise_()
        self.label_19.raise_()

        self.pushButton_2.clicked.connect(self.tabelmenu)
        self.toolButton.clicked.connect(self.browser)
        self.pushButton.clicked.connect(self.klasifikasi)
        self.horizontalSlider.valueChanged.connect(self.updatelabel)
        self.pushButton_3.clicked.connect(self.frekuensikata)
        self.pushButton_4.clicked.connect(self.frekuensikata)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Filename"))
        self.label.setText(_translate("Form", "Upload File CSV"))
        self.toolButton.setText(_translate("Form", "Select File"))
        self.pushButton.setText(_translate("Form", "Mulai Proses Klasifikasi"))
        self.label_3.setText(_translate("Form", "Hasil Confusion Matrix"))
        self.pushButton_2.setText(_translate(
            "Form", "Lihat Hasil Klafisikasi"))
        self.label_4.setText(_translate(
            "Form", "*Membutukan data yang telah di preprocessing"))
        self.label_5.setText(_translate("Form", "NB Accuaracy       : "))
        self.label_6.setText(_translate("Form", "NB Precision          :"))
        self.label_7.setText(_translate("Form", "NB Recall               : "))
        self.label_8.setText(_translate(
            "Form", "NB f1                     : "))
        self.label_11.setText(_translate("Form", "Confusion matrix   :"))
        self.label_17.setText(_translate("Form", "Klasifikasi Report"))
        self.label_9.setText(_translate("Form", "Atur Split Data"))
        self.label_12.setText(_translate("Form", "Data Train"))
        self.label_13.setText(_translate("Form", "Data Test"))
        self.label_14.setText(_translate("Form", "0%"))
        self.label_15.setText(_translate("Form", "100%"))
        self.label_10.setText(_translate("Form", "Data Train :"))
        self.label_16.setText(_translate("Form", "Data Test  :"))
        self.pushButton_3.setText(_translate("Form", "Frekuensi Kata Negatif"))
        self.pushButton_4.setText(_translate("Form", "Frekuensi Kata Positif"))
        self.label_18.setText(_translate(
            "Form", "Klasfikasi Naive Bayes Clasifier"))
        self.label_19.setText(_translate("Form", " "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
